cimport pyforms
from cpython cimport array
import array
from enum import IntEnum

cdef int _enumval_counter = 0

cdef _enumval(int start = -1):
    global _enumval_counter
    if start != -1:
        _enumval_counter = start
    result = _enumval_counter
    _enumval_counter += 1
    return result

cdef class PYFL_FORM:
    cdef pyforms.FL_FORM* _fl_handle

cdef class PYFL_OBJECT:
    cdef pyforms.FL_OBJECT* _fl_handle

# +-- Colors (FL_PD_COL)
PYFL_BLACK = FL_BLACK
PYFL_RED = FL_RED
PYFL_GREEN = FL_GREEN
PYFL_YELLOW = FL_YELLOW
PYFL_BLUE = FL_BLUE
PYFL_MAGENTA = FL_MAGENTA
PYFL_CYAN = FL_CYAN
PYFL_WHITE = FL_WHITE
PYFL_TOMATO = FL_TOMATO
PYFL_INDIANRED = FL_INDIANRED
PYFL_SLATEBLUE = FL_SLATEBLUE
PYFL_COL1 = FL_COL1
PYFL_RIGHT_BCOL = FL_RIGHT_BCOL
PYFL_BOTTOM_BCOL = FL_BOTTOM_BCOL
PYFL_TOP_BCOL = FL_TOP_BCOL
PYFL_LEFT_BCOL = FL_LEFT_BCOL
PYFL_MCOL = FL_MCOL
PYFL_INACTIVE = FL_INACTIVE
PYFL_PALEGREEN = FL_PALEGREEN
PYFL_DARKGOLD = FL_DARKGOLD
PYFL_ORCHID = FL_ORCHID
PYFL_DARKCYAN = FL_DARKCYAN
PYFL_DARKTOMATO = FL_DARKTOMATO
PYFL_WHEAT = FL_WHEAT
PYFL_DARKORANGE = FL_DARKORANGE
PYFL_DEEPPINK = FL_DEEPPINK
PYFL_CHARTREUSE = FL_CHARTREUSE
PYFL_DARKVIOLET = FL_DARKVIOLET
PYFL_SPRINGGREEN = FL_SPRINGGREEN
PYFL_DODGERBLUE = FL_DODGERBLUE
PYFL_LIGHTER_COL1 = FL_LIGHTER_COL1
PYFL_DARKER_COL1 = FL_DARKER_COL1
PYFL_ALICEBLUE = FL_ALICEBLUE
PYFL_ANTIQUEWHITE = FL_ANTIQUEWHITE
PYFL_AQUA = FL_AQUA
PYFL_AQUAMARINE = FL_AQUAMARINE
PYFL_AZURE = FL_AZURE
PYFL_BEIGE = FL_BEIGE
PYFL_BISQUE = FL_BISQUE
PYFL_BLANCHEDALMOND = FL_BLANCHEDALMOND
PYFL_BLUEVIOLET = FL_BLUEVIOLET
PYFL_BROWN = FL_BROWN
PYFL_BURLYWOOD = FL_BURLYWOOD
PYFL_CADETBLUE = FL_CADETBLUE
PYFL_CHOCOLATE = FL_CHOCOLATE
PYFL_CORAL = FL_CORAL
PYFL_CORNFLOWERBLUE = FL_CORNFLOWERBLUE
PYFL_CORNSILK = FL_CORNSILK
PYFL_CRIMSON = FL_CRIMSON
PYFL_DARKBLUE = FL_DARKBLUE
PYFL_DARKGOLDENROD = FL_DARKGOLDENROD
PYFL_DARKGRAY = FL_DARKGRAY
PYFL_DARKGREEN = FL_DARKGREEN
PYFL_DARKGREY = FL_DARKGREY
PYFL_DARKKHAKI = FL_DARKKHAKI
PYFL_DARKMAGENTA = FL_DARKMAGENTA
PYFL_DARKOLIVEGREEN = FL_DARKOLIVEGREEN
PYFL_DARKORCHID = FL_DARKORCHID
PYFL_DARKRED = FL_DARKRED
PYFL_DARKSALMON = FL_DARKSALMON
PYFL_DARKSEAGREEN = FL_DARKSEAGREEN
PYFL_DARKSLATEBLUE = FL_DARKSLATEBLUE
PYFL_DARKSLATEGRAY = FL_DARKSLATEGRAY
PYFL_DARKSLATEGREY = FL_DARKSLATEGREY
PYFL_DARKTURQUOISE = FL_DARKTURQUOISE
PYFL_DEEPSKYBLUE = FL_DEEPSKYBLUE
PYFL_DIMGRAY = FL_DIMGRAY
PYFL_DIMGREY = FL_DIMGREY
PYFL_FIREBRICK = FL_FIREBRICK
PYFL_FLORALWHITE = FL_FLORALWHITE
PYFL_FORESTGREEN = FL_FORESTGREEN
PYFL_FUCHSIA = FL_FUCHSIA
PYFL_GAINSBORO = FL_GAINSBORO
PYFL_GHOSTWHITE = FL_GHOSTWHITE
PYFL_GOLD = FL_GOLD
PYFL_GOLDENROD = FL_GOLDENROD
PYFL_GRAY = FL_GRAY
PYFL_GREENYELLOW = FL_GREENYELLOW
PYFL_GREY = FL_GREY
PYFL_HONEYDEW = FL_HONEYDEW
PYFL_HOTPINK = FL_HOTPINK
PYFL_INDIGO = FL_INDIGO
PYFL_IVORY = FL_IVORY
PYFL_KHAKI = FL_KHAKI
PYFL_LAVENDER = FL_LAVENDER
PYFL_LAVENDERBLUSH = FL_LAVENDERBLUSH
PYFL_LAWNGREEN = FL_LAWNGREEN
PYFL_LEMONCHIFFON = FL_LEMONCHIFFON
PYFL_LIGHTBLUE = FL_LIGHTBLUE
PYFL_LIGHTCORAL = FL_LIGHTCORAL
PYFL_LIGHTCYAN = FL_LIGHTCYAN
PYFL_LIGHTGOLDENRODYELLOW = FL_LIGHTGOLDENRODYELLOW
PYFL_LIGHTGRAY = FL_LIGHTGRAY
PYFL_LIGHTGREEN = FL_LIGHTGREEN
PYFL_LIGHTGREY = FL_LIGHTGREY
PYFL_LIGHTPINK = FL_LIGHTPINK
PYFL_LIGHTSALMON = FL_LIGHTSALMON
PYFL_LIGHTSEAGREEN = FL_LIGHTSEAGREEN
PYFL_LIGHTSKYBLUE = FL_LIGHTSKYBLUE
PYFL_LIGHTSLATEGRAY = FL_LIGHTSLATEGRAY
PYFL_LIGHTSLATEGREY = FL_LIGHTSLATEGREY
PYFL_LIGHTSTEELBLUE = FL_LIGHTSTEELBLUE
PYFL_LIGHTYELLOW = FL_LIGHTYELLOW
PYFL_LIME = FL_LIME
PYFL_LIMEGREEN = FL_LIMEGREEN
PYFL_LINEN = FL_LINEN
PYFL_MAROON = FL_MAROON
PYFL_MEDIUMAQUAMARINE = FL_MEDIUMAQUAMARINE
PYFL_MEDIUMBLUE = FL_MEDIUMBLUE
PYFL_MEDIUMORCHID = FL_MEDIUMORCHID
PYFL_MEDIUMPURPLE = FL_MEDIUMPURPLE
PYFL_MEDIUMSEAGREEN = FL_MEDIUMSEAGREEN
PYFL_MEDIUMSLATEBLUE = FL_MEDIUMSLATEBLUE
PYFL_MEDIUMSPRINGGREEN = FL_MEDIUMSPRINGGREEN
PYFL_MEDIUMTURQUOISE = FL_MEDIUMTURQUOISE
PYFL_MEDIUMVIOLETRED = FL_MEDIUMVIOLETRED
PYFL_MIDNIGHTBLUE = FL_MIDNIGHTBLUE
PYFL_MINTCREAM = FL_MINTCREAM
PYFL_MISTYROSE = FL_MISTYROSE
PYFL_MOCCASIN = FL_MOCCASIN
PYFL_NAVAJOWHITE = FL_NAVAJOWHITE
PYFL_NAVY = FL_NAVY
PYFL_OLDLACE = FL_OLDLACE
PYFL_OLIVE = FL_OLIVE
PYFL_OLIVEDRAB = FL_OLIVEDRAB
PYFL_ORANGE = FL_ORANGE
PYFL_ORANGERED = FL_ORANGERED
PYFL_PALEGOLDENROD = FL_PALEGOLDENROD
PYFL_PALETURQUOISE = FL_PALETURQUOISE
PYFL_PALEVIOLETRED = FL_PALEVIOLETRED
PYFL_PAPAYAWHIP = FL_PAPAYAWHIP
PYFL_PEACHPUFF = FL_PEACHPUFF
PYFL_PERU = FL_PERU
PYFL_PINK = FL_PINK
PYFL_PLUM = FL_PLUM
PYFL_POWDERBLUE = FL_POWDERBLUE
PYFL_PURPLE = FL_PURPLE
PYFL_ROSYBROWN = FL_ROSYBROWN
PYFL_ROYALBLUE = FL_ROYALBLUE
PYFL_SADDLEBROWN = FL_SADDLEBROWN
PYFL_SALMON = FL_SALMON
PYFL_SANDYBROWN = FL_SANDYBROWN
PYFL_SEAGREEN = FL_SEAGREEN
PYFL_SEASHELL = FL_SEASHELL
PYFL_SIENNA = FL_SIENNA
PYFL_SILVER = FL_SILVER
PYFL_SKYBLUE = FL_SKYBLUE
PYFL_SLATEGRAY = FL_SLATEGRAY
PYFL_SLATEGREY = FL_SLATEGREY
PYFL_SNOW = FL_SNOW
PYFL_STEELBLUE = FL_STEELBLUE
PYFL_TAN = FL_TAN
PYFL_TEAL = FL_TEAL
PYFL_THISTLE = FL_THISTLE
PYFL_TURQUOISE = FL_TURQUOISE
PYFL_VIOLET = FL_VIOLET
PYFL_WHITESMOKE = FL_WHITESMOKE
PYFL_YELLOWGREEN = FL_YELLOWGREEN
PYFL_COLOR_CHOOSER_COLOR = FL_COLOR_CHOOSER_COLOR
PYFL_FREE_COL1 = FL_FREE_COL1
PYFL_FREE_COL2 = FL_FREE_COL2
PYFL_FREE_COL3 = FL_FREE_COL3
PYFL_FREE_COL4 = FL_FREE_COL4
PYFL_FREE_COL5 = FL_FREE_COL5
PYFL_FREE_COL6 = FL_FREE_COL6
PYFL_FREE_COL7 = FL_FREE_COL7
PYFL_FREE_COL8 = FL_FREE_COL8
PYFL_FREE_COL9 = FL_FREE_COL9
PYFL_FREE_COL10 = FL_FREE_COL10
PYFL_FREE_COL11 = FL_FREE_COL11
PYFL_FREE_COL12 = FL_FREE_COL12
PYFL_FREE_COL13 = FL_FREE_COL13
PYFL_FREE_COL14 = FL_FREE_COL14
PYFL_FREE_COL15 = FL_FREE_COL15
PYFL_FREE_COL1 = FL_FREE_COL1
PYFL_NOCOLOR = FL_NOCOLOR
# --+

PYFL_FULLBORDER = FL_FULLBORDER
PYFL_TRANSIENT = FL_TRANSIENT
PYFL_NOBORDER = FL_NOBORDER

ctypedef int PYFL_Coord 

ctypedef unsigned long PYFL_COLOR

ctypedef unsigned long PYXID

ctypedef int PYFL_BOX_TYPE
PYFL_UP_BOX = 1

ctypedef int PYFL_BUTTON_TYPE
PYFL_NORMAL_BUTTON = _enumval(0)

ctypedef int PYFL_PLACE
PYFL_PLACE_MOUSE = 1

ctypedef int PYFL_BORDER

def pyfl_initialize(char* appclass):
    cdef int argc = 1
    cdef array.array argv = array.array('b', 'pyforms')
    pyforms.fl_initialize(&argc, <char**>&argv.data.as_voidptr, appclass, <void*>0, 0)

def pyfl_bgn_form(int type, PYFL_Coord w, PYFL_Coord h):
    cdef PYFL_FORM result = PYFL_FORM()
    result._fl_handle = pyforms.fl_bgn_form(type, w, h)
    return result

def pyfl_add_button(int type, PYFL_Coord x, PYFL_Coord y, PYFL_Coord w, PYFL_Coord h, char* label):
    cdef PYFL_OBJECT result = PYFL_OBJECT()
    result._fl_handle = pyforms.fl_add_button(type, x, y, w, h, label)
    return result

def pyfl_end_form():
    pyforms.fl_end_form()

def pyfl_show_form(PYFL_FORM form, PYFL_PLACE place, PYFL_BORDER border, char* name):
    cdef PYXID result = pyforms.fl_show_form(form._fl_handle, place, border, name)
    return result

def pyfl_do_forms():
    cdef PYFL_OBJECT result = PYFL_OBJECT()
    result._fl_handle = pyforms.fl_do_forms()
    return result

def pyfl_hide_form(PYFL_FORM form):
    pyforms.fl_hide_form(form._fl_handle)

def pyfl_get_form_background_color(PYFL_FORM form):
    cdef PYFL_COLOR result = pyforms.fl_get_form_background_color(form._fl_handle)
    return result

def pyfl_set_form_background_color(PYFL_FORM form, PYFL_COLOR color):
    pyforms.fl_set_form_background_color(form._fl_handle, color)

def pyfl_set_object_helper(PYFL_OBJECT obj, char* tip):
    pyforms.fl_set_object_helper(obj._fl_handle, tip)

def pyfl_get_font_name(int n):
    result = pyforms.fl_get_font_name(n)
    return result

def pyfl_set_font_name(int n, char* name):
    result = pyforms.fl_set_font_name(n, name)
    return result

def pyfl_set_object_color(PYFL_OBJECT obj, PYFL_COLOR col1, PYFL_COLOR col2):
    pyforms.fl_set_object_color(obj._fl_handle, col1, col2)

