@node Part II
@unnumbered @emph{Part II - The Form Designer}

@menu
* Part II Introduction::
* Part II Getting Started::
* Part II Command Line Arguments::
* Part II Creating Forms::
* Part II Saving and Loading Forms::
* Part II Language Filters::
* Part II Generating Hardcopies::
@end menu

@include part2_introduction.texi
@include part2_getting_started.texi
@include part2_command_line.texi
@include part2_creating_forms.texi
@include part2_saving_loading.texi
@include part2_language_filters.texi
@include part2_generating_hardcopies.texi
