/* Header file generated by fdesign on Sat Sep 17 15:12:01 2016 */

#ifndef FD_choiceattrib_h_
#define FD_choiceattrib_h_

#include  "../lib/include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void add_choice_item_cb( FL_OBJECT *, long );
void delete_choice_item_cb( FL_OBJECT *, long );
void change_choice_item_cb( FL_OBJECT *, long );
void clear_choice_field_cb( FL_OBJECT *, long );
void replace_choice_item_cb( FL_OBJECT *, long );
void choice_align_cb( FL_OBJECT *, long );
void choice_val_cb( FL_OBJECT *, long );
void use_struct_cb( FL_OBJECT *, long );
void choiceentry_scope_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * choiceattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * content_br;
    FL_OBJECT * input;
    FL_OBJECT * auto_clear;
    FL_OBJECT * mode;
    FL_OBJECT * shortcut;
    FL_OBJECT * align;
    FL_OBJECT * val;
    FL_OBJECT * new_menuapi;
    FL_OBJECT * scope;
} FD_choiceattrib;

FD_choiceattrib * create_form_choiceattrib( void );

#if defined __cplusplus
}
#endif

#endif /* FD_choiceattrib_h_ */
