/* Header file generated by fdesign on Sat Sep 17 15:12:01 2016 */

#ifndef FD_freeobjattrib_h_
#define FD_freeobjattrib_h_

#include  "../lib/include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void handler_name_change_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * freeobjattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * hname;
} FD_freeobjattrib;

FD_freeobjattrib * create_form_freeobjattrib( void );

#if defined __cplusplus
}
#endif

#endif /* FD_freeobjattrib_h_ */
