/* Header file generated by fdesign on Sat Sep 17 15:12:01 2016 */

#ifndef FD_spinnerattrib_h_
#define FD_spinnerattrib_h_

#include  "../lib/include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void spn_precision_cb( FL_OBJECT *, long );
void spn_minmax_change( FL_OBJECT *, long );
void spn_returnsetting_change( FL_OBJECT *, long );
void spn_initialvalue_change( FL_OBJECT *, long );
void spn_stepchange_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * spinnerattrib;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * background;
    FL_OBJECT * prec;
    FL_OBJECT * minval;
    FL_OBJECT * maxval;
    FL_OBJECT * returnsetting;
    FL_OBJECT * initialval;
    FL_OBJECT * step;
} FD_spinnerattrib;

FD_spinnerattrib * create_form_spinnerattrib( void );

#if defined __cplusplus
}
#endif

#endif /* FD_spinnerattrib_h_ */
