/* Header file generated by fdesign on Sat Feb  2 20:43:51 2019 */

#ifndef FD_fbform_h_
#define FD_fbform_h_

#include  "include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void sort_method_cb( FL_OBJECT *, long );
void done_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * fbform;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * browser;
    FL_OBJECT * total;
} FD_fbform;

FD_fbform * create_form_fbform( void );

#if defined __cplusplus
}
#endif

#endif /* FD_fbform_h_ */
