/* Form definition file generated by fdesign on Sat Feb  2 20:43:51 2019 */

#include <stdlib.h>
#include "fbtest_gui.h"


/***************************************
 ***************************************/

FD_fbform *
create_form_fbform( void )
{
    FL_OBJECT *obj;
    FD_fbform *fdui = ( FD_fbform * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->fbform = fl_bgn_form( FL_NO_BOX, 371, 361 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 371, 361, "" );

    fdui->browser = obj = fl_add_browser( FL_NORMAL_BROWSER, 20, 50, 240, 290, "" );
    fl_set_object_color( obj, FL_COL1, FL_YELLOW );

    obj = fl_add_checkbutton( FL_RADIO_BUTTON, 270, 50, 70, 25, "AlphaSort" );
    fl_set_object_callback( obj, sort_method_cb, FL_ALPHASORT );
    fl_set_button( obj, 1 );

    obj = fl_add_checkbutton( FL_RADIO_BUTTON, 270, 85, 70, 25, "SizeSort" );
    fl_set_object_callback( obj, sort_method_cb, FL_SIZESORT );

    obj = fl_add_checkbutton( FL_RADIO_BUTTON, 270, 120, 70, 25, "TimeSort" );
    fl_set_object_callback( obj, sort_method_cb, FL_MTIMESORT );

    obj = fl_add_button( FL_NORMAL_BUTTON, 275, 310, 75, 25, "Done" );
    fl_set_object_callback( obj, done_cb, 0 );

    fdui->total = obj = fl_add_text( FL_NORMAL_TEXT, 10, 15, 220, 30, "" );
    fl_set_object_boxtype( obj, FL_NO_BOX );

    fl_end_form( );

    fdui->fbform->fdui = fdui;

    return fdui;
}
