/* Header file generated by fdesign on Sat Feb  2 20:43:53 2019 */

#ifndef FD_buttonform_h_
#define FD_buttonform_h_

#include  "include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */



void done_cb( FL_OBJECT *, long );
void hide_show_cb( FL_OBJECT *, long );
void reshow_cb( FL_OBJECT *, long );
void scroll_cb( FL_OBJECT *, long );
void deactivate_cb( FL_OBJECT *, long );






/* Forms and Objects */

typedef struct {
    FL_FORM   * buttonform;
    void      * vdata;
    char      * cdata;
    long        ldata;
} FD_buttonform;

FD_buttonform * create_form_buttonform( void );
typedef struct {
    FL_FORM   * staticform;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * chart;
} FD_staticform;

FD_staticform * create_form_staticform( void );
typedef struct {
    FL_FORM   * mainform;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * done;
    FL_OBJECT * hide;
    FL_OBJECT * show;
    FL_OBJECT * reshow;
    FL_OBJECT * set;
    FL_OBJECT * deactivate;
    FL_OBJECT * formbrowser;
} FD_mainform;

FD_mainform * create_form_mainform( void );
typedef struct {
    FL_FORM   * valuatorform;
    void      * vdata;
    char      * cdata;
    long        ldata;
} FD_valuatorform;

FD_valuatorform * create_form_valuatorform( void );
typedef struct {
    FL_FORM   * choiceform;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * pulldown;
    FL_OBJECT * choice;
    FL_OBJECT * browser;
    FL_OBJECT * pushmenu;
} FD_choiceform;

FD_choiceform * create_form_choiceform( void );
typedef struct {
    FL_FORM   * inputform;
    void      * vdata;
    char      * cdata;
    long        ldata;
} FD_inputform;

FD_inputform * create_form_inputform( void );
typedef struct {
    FL_FORM   * big;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * xyplot;
} FD_big;

FD_big * create_form_big( void );

#if defined __cplusplus
}
#endif

#endif /* FD_buttonform_h_ */
