/* Form definition file generated by fdesign on Sat Feb  2 20:43:57 2019 */

#include <stdlib.h>
#include "inputall_gui.h"


/***************************************
 ***************************************/

FD_input *
create_form_input( void )
{
    FL_OBJECT *obj;
    FD_input *fdui = ( FD_input * ) fl_malloc( sizeof *fdui );

    fdui->vdata = fdui->cdata = NULL;
    fdui->ldata = 0;

    fdui->input = fl_bgn_form( FL_NO_BOX, 441, 441 );

    obj = fl_add_box( FL_UP_BOX, 0, 0, 441, 441, "" );

    fdui->norminput = obj = fl_add_input( FL_NORMAL_INPUT, 40, 40, 340, 30, "Normal Input" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );
    fl_set_object_callback( obj, input_cb, 0 );

    fdui->intinput = obj = fl_add_input( FL_INT_INPUT, 40, 100, 160, 30, "Integer Input" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );
    fl_set_object_callback( obj, input_cb, 0 );

    fdui->floatinput = obj = fl_add_input( FL_FLOAT_INPUT, 230, 100, 160, 30, "Float Input" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );
    fl_set_object_callback( obj, input_cb, 0 );

    fdui->dateinput = obj = fl_add_input( FL_DATE_INPUT, 40, 150, 160, 30, "Date Input" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );
    fl_set_object_callback( obj, input_cb, 0 );

    fdui->secretinput = obj = fl_add_input( FL_SECRET_INPUT, 230, 150, 160, 30, "Secret Input" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );
    fl_set_object_callback( obj, input_cb, 0 );

    fdui->multiinput = obj = fl_add_input( FL_MULTILINE_INPUT, 40, 210, 360, 180, "Multi-line input" );
    fl_set_object_lalign( obj, FL_ALIGN_LEFT_TOP );
    fl_set_object_callback( obj, input_cb, 0 );

    fdui->report = obj = fl_add_text( FL_NORMAL_TEXT, 30, 400, 210, 30, "" );

    obj = fl_add_button( FL_NORMAL_BUTTON, 330, 400, 70, 30, "Done" );
    fl_set_object_callback( obj, done_cb, 0 );

    obj = fl_add_button( FL_NORMAL_BUTTON, 250, 400, 70, 30, "Hide/Show" );
    fl_set_object_callback( obj, hide_show_cb, 0 );

    fl_end_form( );

    fdui->input->fdui = fdui;

    return fdui;
}
