/* Header file generated by fdesign on Sat Feb  2 20:44:06 2019 */

#ifndef FD_scb_h_
#define FD_scb_h_

#include  "include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void noop_cb( FL_OBJECT *, long );
void hide_cb( FL_OBJECT *, long );
void deactivate_cb( FL_OBJECT *, long );
void done_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * scb;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * hor;
    FL_OBJECT * hor_thin;
    FL_OBJECT * hor_nice;
    FL_OBJECT * vert;
    FL_OBJECT * vert_thin;
    FL_OBJECT * hide;
    FL_OBJECT * deactivate;
    FL_OBJECT * vert_nice;
} FD_scb;

FD_scb * create_form_scb( void );

#if defined __cplusplus
}
#endif

#endif /* FD_scb_h_ */
