/* Header file generated by fdesign on Sat Feb  2 20:44:10 2019 */

#ifndef FD_twheelform_h_
#define FD_twheelform_h_

#include  "include/forms.h" 

#if defined __cplusplus
extern "C"
{
#endif

/* Callbacks, globals and object handlers */

void valchange_cb( FL_OBJECT *, long );
void returnchange_cb( FL_OBJECT *, long );


/* Forms and Objects */

typedef struct {
    FL_FORM   * twheelform;
    void      * vdata;
    char      * cdata;
    long        ldata;
    FL_OBJECT * vert;
    FL_OBJECT * hor;
    FL_OBJECT * report;
    FL_OBJECT * returnsetting;
} FD_twheelform;

FD_twheelform * create_form_twheelform( void );

#if defined __cplusplus
}
#endif

#endif /* FD_twheelform_h_ */
